### ISSUE TITLE
Still says the same error

### ISSUE THREAD

**Issue by kataramamra** [ambiennt/KeyPatcher#1]
Sooo, when i patched the Minecraft.Windows.Exe using mclauncher it still said "couldnt validate your microsoft acc" when i redownloaded it, i tried patching it multiple times and redownloading it, but every time i was faced with the same error.

**Comment by ambiennt** [comment]
Can you provide a more detailed list of steps to reproduce the issue? I have tested this program on my own and in a virtual machine with 100% success, and others have reported success as well. I assume you read the entire README, correct?

**Comment by Jaciezyt** [comment]
Maybe the server-side public key isn't updated.
If you are attemped to connect to a BDS, you must add `trusted-key=MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAECRXueJeTDqNRRgJi/vlRufByu/2G0i2Ebt6YMar5QX/R0DIIyrJMcUpruK4QveTfJSTp3Shlq4Gk34cD/4GUWwkv0DVuzeuB+tXija7HBxii03NHDbPAD0AKnLr2wdAp` to server.properties
