### ISSUE TITLE
Infinite loading?

### ISSUE THREAD

**Issue by kzwa01** [ambiennt/KeyPatcher#4]
I'm not sure if the issue is on my end or due to the patching, but I've followed all the steps and even installed your pre-patched .appx file. Every time I join a server that allows version 1.18.12, I encounter an infinite loading screen until I eventually get a connection timed out error. Is there any fix for this, or am I stuck?

**Comment by ambiennt** [comment]
Maybe the server isn't using the new public key

**Comment by kzwa01** [comment]
I’m trying to connect to 2b2tpe.org and other Infinite Games Network servers, but I keep getting stuck in an infinite loading screen. If you still have your patched version, maybe you could give it a shot? I’ve seen a lot of others playing on version 1.18.12, so it seems like this issue is just happening to me.

**Comment by ambiennt** [comment]
> 2b2tpe.org

According to [this website](https://minecraftpocket-servers.com/server/79685/), the server you mentioned only supports 1.19

**Comment by kzwa01** [comment]
That was it, guess im a little stupid. thank you.
